 create table personel (
       id integer generated by default as identity,
        adi varchar(255),
        email varchar(255),
        bolum_id integer,
        primary key (id)
    );
    alter table personel 
       add constraint FKbmg4bi4mpnuee6mtpg8tn0q8e 
       foreign key (bolum_id) 
       references bolum;